Repository Path-Check/safeplaces-backend, pull requests merged in 2020-07, with the labels that each got.

#189 [Auth] Use realm instead of connection
  .DS_Store
  .env.template
  .github/workflows/google-express-tests.yaml
  .github/workflows/integration-tests.yaml
  app/api/auth/controller.js
  app/auth/utils.js
Labels: bug

#191 Integrate auth library
  app/api/auth/controller.js
  app/auth/enforce/common.js
  app/auth/enforce/index.js
  app/auth/enforce/prod.js
  app/auth/enforce/test.js
  app/auth/index.js
  app/auth/utils.js
  package-lock.json
  package.json
  src/server/express.js
  test/integration/accessCode.test.js
  test/integration/case.test.js
  test/integration/login.test.js
  test/integration/organizations.test.js
  test/integration/upload.test.js
  tests/tests/backend_collection.json
Labels: do not merge, enhancement, security

#193 [Tiny change] Remove deprecated "/login" endpoint
  app/api/auth/router.js
  tests/tests/backend_collection.json
Labels: do not merge, security

#195 Small fix
  app.js
  package-lock.json
  package.json
  tests/tests/backend_collection.json
Labels: bug

#207 [Hotfix] Support cookie domain
  .env.template
  app/api/auth/controller.js
  app/lib/auth.js
  env.schema.json
  package-lock.json
  package.json
Labels: enhancement

#209 Bump data layer version 0.1.5 ⟶ 0.1.6
  package.json
Labels: dependencies

#211 Add 3 Newman tests for contact tracer user
  tests/tests/backend_collection.json
Labels: enhancement

#212 Update env schema
  env.schema.json
Labels: enhancement

#200 Move points related endpoints over to translation service
  app/api/case/controller.js
  app/api/case/router.js
  app/lib/geoHash.js
  app/lib/pocTransform.js
  app/lib/publicationFiles.js
  package-lock.json
  package.json
  test/integration/case.test.js
  test/integration/upload.test.js
  test/unit/geoHash.test.js
  test/unit/transformDuration.test.js
Labels: do not merge

#213 Add CSRF protection and fix tests
  package-lock.json
  package.json
  test/integration/accessCode.test.js
  test/integration/case.test.js
  test/integration/login.test.js
  test/integration/organizations.test.js
  tests/tests/backend_collection.json
Labels: enhancement, security

#229 User management
  .env.template
  .github/workflows/google-express-tests.yaml
  .github/workflows/integration-tests.yaml
  app.js
  app/api/auth/controller.js
  app/api/auth/router.js
  app/lib/auth.js
  app/lib/policy.js
  app/lib/userManagement.js
  package-lock.json
  package.json
  test/integration/login.test.js
  test/integration/users.test.js
Labels: enhancement, ready for review
