Repository Path-Check/safeplaces-backend, pull requests merged in 2020-06, with the labels that each got.

#79 Implement authentication middleware and LDAP server
  .env.template
  .gitignore
  AUTHENTICATION.md
  Dockerfile
  README.md
  app/api/auth/controller.js
  app/api/auth/router.js
  ldapjs/README.md
  ldapjs/index.js
  ldapjs/ldapServer.js
  ldapjs/package.json
  ldapjs/passwd
  ldapjs/yarn.lock
  package-lock.json
  package.json
  src/server/express.js
  src/server/passport.js
  test/integration/case.test.js
  test/integration/login.test.js
  test/integration/organizations.test.js
  test/integration/point.test.js
  test/integration/redacted.test.js
  test/integration/safepaths.test.js
Labels: enhancement, expressjs, ready for review

#83 Extract LDAP environment variables and document usage
  .env.template
  .gitignore
  README.md
  ldapjs/ldapServer.js
  src/server/passport.js
Labels: enhancement, expressjs

#84 Modify LDAP environment variables to ensure compat with OpenLDAP
  .env.template
  README.md
Labels: bug

#87 Places-281 OpenLDAP and ldapjs compatability
  .env.template
  .github/workflows/google-express-tests.yaml
  .github/workflows/google-express.yml
  .github/workflows/google-nest.yml
  README.md
  app/api/auth/controller.js
  ldapjs/ldapServer.js
  ldapjs/passwd
  src/server/passport.js
  test/integration/login.test.js
Labels: bug, expressjs

#118 Logging
  .github/workflows/google-express.yml
  app/api/case/controller.js
  app/api/health/controller.js
  app/api/health/router.js
  app/api/organization/controller.js
  app/lib/pocTransform.js
  ldapjs/ldapServer.js
  package-lock.json
  package.json
  src/index.js
  src/logger/config.js
  src/logger/express.js
  src/logger/index.js
  src/logger/transports.js
  src/server/errorHandler.js
  src/server/express.js
  src/server/notFoundHandler.js
  src/server/passport.js
  src/server/responseTimeHandler.js
  yarn.lock
Labels: enhancement, expressjs, ready for review

#141 [PLACES-338] Patch LDAP injection vulnerability on login
  .env.template
  .github/workflows/intergation-tests.yaml
  .gitignore
  README.md
  base/env/test/deployment.yml
  ldapjs/ldapServer.js
  package-lock.json
  package.json
  src/server/passport.js
  test/integration/login.test.js
  tests/tests/FASTAPI.postman_environment.json
Labels: bug

#156 [CI] Speed up integration tests by ~15%
  .github/workflows/integration-tests.yaml
Labels: enhancement

#162 [Hotfix JWT] Fix JWT expiration
  app/api/auth/controller.js
  src/server/passport.js
Labels: bug

#138 Decoupling database layer into it's own library.
  .DS_Store
  .env.template
  Dockerfile
  README.md
  app/api/accessCode/controller.js
  app/api/case/controller.js
  app/api/organization/controller.js
  app/lib/db.js
  db/common/service.js
  db/knex.js
  db/migrations/20200420011121_update_ts.js
  db/migrations/20200428173125_extension_postgis.js
  db/migrations/20200526095904_rebuild.js
  db/migrations/20200528162707_add_expires_at_cases.js
  db/migrations/20200528205533_rename_trails_points.js
  db/migrations/20200529140140_add_privacy_policy_url_to_org.js
  db/migrations/20200531080647_add_onboarding_to_org.js
  db/migrations/20200601143149_add_external_id_to_cases.js
  db/migrations/20200602125508_remove_start_end_date_pubs.js
  db/migrations/20200602184050_points_upload_id.js
  db/migrations/20200603105100_add_consented_to_publishing_at_cases.js
  db/migrations/20200605094523_add_duration_to_points.js
  db/migrations/20200605161325_cases_contact_tracer_id.js
  db/migrations/20200605163716_cases_staged_at.js
  db/migrations/20200611164840_organizations_external_id.js
  db/migrations/20200612151326_chag_timeframe.js
  db/models/accessCodes.js
  db/models/cases.js
  db/models/organizations.js
  db/models/points.js
  db/models/publicOrganizations.js
  db/models/publications.js
  db/models/settings.js
  db/models/upload.js
  db/models/users.js
  db/seeds/development/organizations_seed.js
  db/seeds/development/users_seed.js
  db/seeds/test/organizations_seed.js
  db/seeds/test/users_seed.js
  dbsetup.sh
  knexfile-public.js
  knexfile.js
  ldapjs/ldapServer.js
  nestjs/api-spec.json
  package-lock.json
  package.json
  src/server/passport.js
  test/integration/case.test.js
  test/integration/organizations.test.js
  test/integration/upload.test.js
  test/lib/agent.js
  test/lib/mockData.js
  test/unit/sampleTest.test.js
Labels: enhancement, ready for review

#165 Add support for environment variable validation
  .github/workflows/google-express.yml
  .run
  bin/www
  env.schema.json
  package-lock.json
  package.json
  tools/validateEnv.js
Labels: enhancement

#172 [PLACES-336 cont.] Handle access token in cookie
  .eslintrc
  .prettierignore
  app/api/auth/router.js
  app/api/case/controller.js
  app/api/case/index.js
  app/api/case/router.js
  app/api/health/controller.js
  app/api/organization/controller.js
  app/api/organization/router.js
  app/lib/geoHash.js
  app/lib/pocTransform.js
  app/lib/publicationFiles.js
  app/lib/random.js
  app/lib/utils.js
  app/lib/writePublishedFiles.js
  app/lib/writeToGCSBucket.js
  app/lib/writeToS3Bucket.js
  env.schema.json
  package-lock.json
  package.json
  src/logger/config.js
  src/logger/express.js
  src/logger/index.js
  src/logger/transports.js
  src/server/auth.js
  src/server/errorHandler.js
  src/server/express.js
  src/server/notFoundHandler.js
  src/server/passport.js
  src/server/responseTimeHandler.js
  test/integration/accessCode.test.js
  test/integration/case.test.js
  test/integration/health.test.js
  test/integration/login.test.js
  test/integration/organizations.test.js
  test/integration/upload.test.js
  test/lib/mockData.js
  test/unit/geoHash.test.js
  test/unit/hello.test.js
  test/unit/transformDuration.test.js
  tests/tests/backend_collection.json
Labels: enhancement

#174 Auto-request individuals for PR review
  .github/CODEOWNERS
Labels: documentation

#176 Integrate with Auth0
  .DS_Store
  .env.template
  .github/workflows/google-express-tests.yaml
  .github/workflows/integration-tests.yaml
  AUTHENTICATION.md
  README.md
  app/api/auth/controller.js
  app/api/auth/router.js
  app/auth/enforce/common.js
  app/auth/enforce/index.js
  app/auth/enforce/prod.js
  app/auth/enforce/test.js
  app/auth/index.js
  app/auth/utils.js
  env.schema.json
  ldapjs/README.md
  ldapjs/index.js
  ldapjs/ldapServer.js
  ldapjs/package-lock.json
  ldapjs/package.json
  ldapjs/passwd
  ldapjs/yarn.lock
  package-lock.json
  package.json
  src/server/auth.js
  src/server/express.js
  src/server/passport.js
  test/integration/accessCode.test.js
  test/integration/case.test.js
  test/integration/login.test.js
  test/integration/organizations.test.js
  test/integration/upload.test.js
  test/lib/mockData.js
  tests/tests/backend_collection.json
  yarn.lock
Labels: enhancement, ready for review
